config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
    path: "",
    path_names: { sign_in: "Login", sign_out: "Logout", edit: "profile", sign_up: "registration" },
    controllers: { registrations: "registrations" }

  # Users routes
  resources :users, only: [ :index, :show ]  do
    member do
      post :follow
      post :unfollow
    end
  end

  authenticated :user do
    root "posts#index", as: :authenticated_root
  end

  # Posts routes
  resources :posts, only: [ :index, :show, :create, :destroy ] do
    member do
      patch :archive
      patch :unarchive
    end
    collection do
      get :archived
    end
    resources :likes, only: [ :create, :destroy ], shallow: true
    resources :comments, only: [ :create, :destroy ], shallow: true
    resources :bookmarks, only: [ :create, :destroy ], shallow: true
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [ :create ]
  before_action :set_comment, only: [ :destroy ]

  def create
    if @post.user == current_user
      flash[:alert] = "You cannot comment on your own post."
      redirect_to posts_path(@post) and return
    end

    @comment = @post.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to posts_path(@post), notice: "Comment added!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to posts_path(@post), alert: "Unable to add comment." }
      end
    end
  end

  def destroy
  if @comment.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to posts_path(@post), notice: "Comment deleted." }
    end
  else
      respond_to do |format|
        format.html { redirect_to posts_path(@post), alert: "Unable to delete comment." }
      end
  end
  end


  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
    @post = @comment.post
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>" class="d-flex justify-content-between w-100 ">
   <div>
  <strong><%= comment.user.name %> Comment:</strong> <%= comment.content %>
  </div>
  <% if comment.user == current_user %>
    <%= button_to comment_path(comment), 
                  method: :delete, 
                  data: { turbo_confirm: "Are you sure?" }, 
                  class: "btn btn-link p-0 text-muted", style:"font-size: 10px;" do %>
      <i class="bi bi-x-lg"></i>
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
 <%= form_with model: [post, Comment.new], local: false, data: { turbo_frame: "new-comment-post-#{post.id}" }, class: "w-100" do |f| %>
          <%= f.text_field :content, class:"form-control fs-6 mt-2 py-2", placeholder:"Add a comment ....", rows:"1", style:"resize: none; border: 1px solid #dedefc; border-radius: 8px", required: true %>
  <% end %>

app/views/comments/create.turbo_stream.erb
<turbo-stream action="append" target="comments-list-<%= @comment.post.id %>">
  <template>
    <%= render "comment", comment: @comment %>
  </template>
</turbo-stream>

app/views/comments/destroy.turbo_stream.erb
<turbo-stream action="remove" target="<%= dom_id(@comment) %>"></turbo-stream>