config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
    path: "",
    path_names: { sign_in: "Login", sign_out: "Logout", edit: "profile", sign_up: "registration" },
    controllers: { registrations: "registrations" }

  # Users routes
  resources :users, only: [ :index, :show ]  do
    member do
      post :follow
      post :unfollow
    end
  end

  authenticated :user do
    root "posts#index", as: :authenticated_root
  end

  # Posts routes
  resources :posts, only: [ :index, :show, :create, :destroy ] do
    member do
      patch :archive
      patch :unarchive
    end
    collection do
      get :archived
    end
    resources :likes, only: [ :create, :destroy ], shallow: true
    resources :comments, only: [ :create, :destroy ], shallow: true
    resources :bookmarks, only: [ :create, :destroy ], shallow: true
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable, :confirmable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
  has_many :comments
  has_many :bookmarks
  has_many :bookmarked_posts, through: :bookmarks, source: :post
  has_one_attached :avatar

   # Users that the current user is following
   has_many :active_follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
   has_many :following, through: :active_follows, source: :followed
 
   # Users that are following the current user
   has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
   has_many :followers, through: :passive_follows, source: :follower


  validates :name, presence: true, length: { maximum: 20 }
  validates :gender, inclusion: { in: [ "male", "female", "other" ], message: "%{value} is not a valid gender" }, allow_nil: true
  validates :birthday, presence: true, allow_nil: true
  validates :location, length: { maximum: 100 }

   # Methods to follow and unfollow
   def follow(other_user)
    active_follows.create(followed_id: other_user.id)
   end

  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  # Check if the user is following another user
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [ :show, :follow, :unfollow ]

    def index
      if params[:query].present?
        query = "%#{params[:query].downcase}%"
        @users = User.where("LOWER(name) LIKE ? OR LOWER(email) LIKE ?", query, query)
        # Assign the first matched user to @user for the profile section
        if @users.any?
        @user = @users.first
        @posts = Post.where(user_id: @users.pluck(:id)) # Fetch posts of found users
        else
        @user = nil
        @posts = [] # If no users found, set posts to empty array
        end
      else
        @users = []
        @posts = []
        @user = nil
      end
    end


    def show
        @user = User.find(params[:id])
        @posts = @user.posts.joins(:images_attachments).distinct.includes(:likes, :comments)
        @saved = Post.joins(:bookmarks).where("bookmarks.user_id=?", current_user.id).joins(:images_attachments).distinct.
        includes(:likes, :comments) if @user == current_user
        @archivedposts = current_user.posts.archived.order(created_at: :desc)
        @followers = @user.followers
        @following = @user.following
    end

    def update
        if @user.update(user_params)
          respond_to do |format|
            format.turbo_stream { render turbo_stream: turbo_stream.replace("user_profile", partial: "users/profile", locals: { user: @user }) }
            format.html { redirect_to @user, notice: "Profile updated successfully." }
        end
        else
          render :edit, status: :unprocessable_entity
        end
    end

    def follow
      current_user.follow(@user)
      redirect_to @user, notice: "You are now following #{@user.name}."
    end

    def unfollow
      current_user.unfollow(@user)
      redirect_to @user, notice: "You have unfollowed #{@user.name}."
    end

    private
    def user_params
        params.require(:user).permit(:name, :website, :bio, :gender, :birthday, :location, :avatar)
    end

    def set_user
      @user = User.find(params[:id])
    end
end

app/views/users/_post.html.erb
<div class="row row-cols-2 row-cols-sm-3 row-cols-md-4 mx-3 w-100 gap-2">
  <% posts.each do |post| %>
    <div class="col position-relative px-0">
      <%= link_to post_path(post) do %>
        <div class="d-flex justify-content-center align-items-center position-absolute text-white fs-5 fw-bold w-100 h-100 bg-dark bg-opacity-25 transition">
          <span>
            <i class="bi bi-heart-fill fs-6 text-primary"></i>
            <%= post.likes.size %>
            <i class="bi bi-chat-fill fs-6 text-primary"></i>
            <%= post.comments.size %>
          </span>
        </div>
      <% end %>

      <% if post.images.attached? %>
        <%= image_tag post.images.first, class: "img-fluid rounded w-100 h-auto" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/_profile.html.erb
<% if user.present? %>
<div class="row w-60 justify-content-md-center justify-content-center align-items-center" style="padding:30px 60px ; border-bottom: 1px solid #efefef;">
  <div class="d-flex justify-content-center align-item-center" style="width:600px">
    <div class="col-md-3 mt-2 pl-4">
      <%= avatar_or_initial(user, size: 150) %>
    </div>
    <div class="col-md-8 px-0 mr-4">
      <div class="px-0 d-flex justify-content-between align-item-center mt-4 " style="width:370px; margin-left:26px;">
        <p style="font-size: 32px; line-height: 40px; font-weight: 200; padding-left:12px;"> <%= @user.name %> </p>
        <% if @user == current_user %>
        <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-outline-dark pt-1", style: "height: 35px;  line-height: 24px; padding: 0 20px; width: 123px; border-color: #dbdbdb; font-size: 14px; font-weight: bold; margin: 8px 0 0 20px;" %>
        <!-- Button trigger modal -->
        <button type="button" data-bs-toggle="modal" data-bs-target="#exampleModal" , style="  background-color: transparent; border: none;">
          <i class="bi bi-gear fs-3 text-muted"></i>
        </button>
        <% end %>
      </div>
      <div class="row p-3 pt-1">
        <div class="col-12 d-flex justify-content-between align-items-center">
          <p class="h6 font-weight-bold mb-0" style="margin-left:26px;"> <%= @user.email %> </p>
        </div>

        <div class="col-12 w-75 d-flex gap-2 mt-2">
          <div class="d-flex flex-column">
            <button class="h6 font-weight-bold mb-0 border-0 position-relative p-2" style="margin-left:12px; width:110px;" type="button" data-bs-toggle="collapse" data-bs-target="#followersList" aria-expanded="false" aria-controls="followersList">Followers (<%= @user.followers.count %>)</button>
            <div class="collapse" id="followersList">
              <ul class="list-group mt-2">
                <% @user.followers.each do |follower| %>
                <li class="list-group-item">
                  <%= link_to follower.name, user_path(follower) %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>

          <div class="d-flex flex-column">
            <button class="h6 font-weight-bold mb-0 border-0 position-relative p-2" style="margin-left:12px; width:115px;" type="button" data-bs-toggle="collapse" data-bs-target="#followingList" aria-expanded="false" aria-controls="followingList">Following (<%= @user.following.count %>)</button>
            <div class="collapse" id="followingList">
              <ul class="list-group mt-2">
                <% @user.following.each do |followed_user| %>
                <li class="list-group-item">
                  <%= link_to followed_user.name, user_path(followed_user) %>
                </li>
                <% end %>
              </ul>
            </div>
          </div>


          <div class="button">
            <% if current_user != @user %>
            <% if current_user.following?(@user) %>
            <%= button_to "Unfollow", unfollow_user_path(@user), method: :delete, class: "btn btn-danger" %>
            <% else %>
            <%= button_to "Follow", follow_user_path(@user), method: :post, class: "btn btn-primary" %>
            <% end %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
    
  <nav>
        <% if current_user != @user %>
        <div class="nav d-flex justify-content-center mt-4" style="border-top: 1px solid #ddd;" id="nav-tab" role="tablist">
          <button class="nav-link fw-bold py-2 active" id="nav-posts-tab" data-bs-toggle="tab" data-bs-target="#nav-posts" type="button" role="tab" aria-controls="nav-posts" aria-selected="true" style="color: #262626; background: transparent; margin-top: -1px; border-radius:0; border-top: 1px solid #262626;">TOTAL POSTS</button>
        </div>
        <% end %>
  </nav>

<% end %>

app/views/users/index.html.erb
<% if @user.present? %>
  <%= render "users/profile", user: @user %>
<% end %>

<div class="container w-50 mt-4">

<% if @posts.any? %>
  <div id="posts">
  <h4>Search Results:</h4>
    <%= render 'posts/posts_list', posts: @posts %>
  </div>
<% else %>
  <p class="m-2 p-2">No posts found for the searched users.</p>
<% end %> 
</div>

app/views/users/show.html.erb
  <%= render "users/profile", user: @user %>

        <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1"   aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title fs-5" id="exampleModalLabel">Settings</h5>
          <button type="button" class="btn-close border-0" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="list-group text-center">
          <%= link_to "Change password", new_user_password_path, class: "list-group-item list-group-item-action" %>
          <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
          <a href="#" class="list-group-item list-group-item-action" data-bs-dismiss="modal">Cancel</a>
        </div>
      </div>
    </div>
  </div>

    <div class="mt-5 w-100">
      <% if @user == current_user %>
      <nav class="mb-2">
        <div class="nav d-flex justify-content-center" style="border-top: 1px solid #ddd;" id="nav-tab" role="tablist">
          <button class="nav-link fw-bold py-2 active" id="nav-posts-tab" data-bs-toggle="tab" data-bs-target="#nav-posts" type="button" role="tab" aria-controls="nav-posts" aria-selected="true" style="color: #262626; background: transparent; margin-top: -1px; border-radius:0; border-top: 1px solid #262626;">POSTS</button>
          <button class="nav-link fw-bold py-2" id="nav-saved-tab" data-bs-toggle="tab" data-bs-target="#nav-saved" type="button" role="tab" aria-controls="nav-saved" aria-selected="false" style="color:#999; background: transparent; margin-top: -1px; border-radius:0; border-top: 1px solid transparent;">SAVED</button>
          <button class="nav-link fw-bold py-2" id="nav-archived-posts-tab" data-bs-toggle="tab" data-bs-target="#nav-archived-posts" type="button" role="tab" aria-controls="nav-archived-posts" aria-selected="false" style="color:#999; background: transparent; margin-top: -1px; border-radius:0; border-top: 1px solid transparent;">ARCHIVED POSTS</button>
        </div>
      </nav>
      <% end %>
      <div class="tab-content pb-3" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-posts" role="tabpanel" aria-labelledby="nav-posts-tab">
          <div class="w-100 px-4">
           <% if @posts.any? %>
            <%= render "post", {posts: @posts} %>
             <% else %>
            <p class="m-2 p-2 text-center">No posts found.</p>
           <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="nav-saved" role="tabpanel" aria-labelledby="nav-saved-tab">
          <div class="w-100 px-4">
          <% if @saved.any? %>
             <%= render "post", {posts: @saved} %>
            <% else %>
            <p class="m-2 p-2 text-center">No Saved posts found.</p>
          <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="nav-archived-posts" role="tabpanel" aria-labelledby="nav-archived-posts-tab">
          <div class="w-100 px-4">
          <% if @archivedposts.any? %>
            <%= render 'posts/archived' %>
            <% else %>
            <p class="m-2 p-2 text-center">No archived posts found.</p>
          <% end %>
          </div>
        </div>
        </div>
      </div>
    </div>