config/routes.rb
Rails.application.routes.draw do
  root "pages#home"

  devise_for :users,
    path: "",
    path_names: { sign_in: "Login", sign_out: "Logout", edit: "profile", sign_up: "registration" },
    controllers: { registrations: "registrations" }

  # Users routes
  resources :users, only: [ :index, :show ]  do
    member do
      post :follow
      post :unfollow
    end
  end

  authenticated :user do
    root "posts#index", as: :authenticated_root
  end

  # Posts routes
  resources :posts, only: [ :index, :show, :create, :destroy ] do
    member do
      patch :archive
      patch :unarchive
    end
    collection do
      get :archived
    end
    resources :likes, only: [ :create, :destroy ], shallow: true
    resources :comments, only: [ :create, :destroy ], shallow: true
    resources :bookmarks, only: [ :create, :destroy ], shallow: true
  end
end

app/models/post.rb
class Post < ApplicationRecord
  before_create :set_archived_to_false

  belongs_to :user
  has_many_attached :images, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :likers, through: :likes, source: :user, dependent: :destroy
  has_many :comments, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :content, presence: true, length: { maximum: 300 }

  scope :unarchived, -> { where(archived: false)  }
  scope :archived, -> { where(archived: true) }

  def is_belongs_to?(user)
    self.user_id == user.id
  end


  def liked_by?(user)
    likers.exists?(id: user.id)
  end

  def is_bookmarked(user)
    Bookmark.find_by(user_id: user.id, post_id: id)
  end

  private
  def purge_images
    images.purge_later
  end

  def set_archived_to_false
    self.archived ||= false
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post, only: [ :show, :destroy, :archive, :unarchive ]

  def index
    @posts = Post.where(archived: false).includes(:images_attachments, :user, :likes).order(created_at: :desc)
    @post = Post.new
  end


  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: "Post created successfully."
    else
      flash[:alert] = "Something went wrong ..."
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @likes = @post.likes.includes(:user)
    @is_liked = @post.liked_by?(current_user)
    @is_bookmarked = @post.is_bookmarked(current_user)
  end

  def destroy
    if @post.user == current_user
      if @post.destroy
        flash[:notice] = "Post deleted!"
      else
        flash[:alert] = "Something went wrong ..."
      end
    else
      flash[:alert] = "You don't have permission to do that!"
    end
    redirect_to posts_path
  end

  def archive
    if @post.user == current_user
      @post.update(archived: true)

      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.remove("post_#{@post.id}")
        end
        format.html { redirect_to posts_path, notice: "Post archived successfully!" }
      end
    else
      flash[:alert] = "You don't have permission to do that!"
      redirect_to posts_path
    end
  end

  def unarchive
    if @post.user == current_user
      @post.update(archived: false)

     respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("post_#{@post.id}") do
            render partial: "posts/posts_list", locals: { post: @post }
          end
        end
        format.html { redirect_to posts_path, notice: "Post unarchived successfully!" }
      end
    else
      flash[:alert] = "You don't have permission to do that!"
      redirect_to posts_path
    end
  end

  def archived
    @posts = current_user.posts.archived.order(created_at: :desc)
  end


  private

  def find_post
    @post = Post.find_by(id: params[:id])
    return if @post

    flash[:danger] = "Post not found!"
    redirect_to root_path
  end

  def post_params
    params.require(:post).permit(:content, images: [])
  end
end

app/views/posts/_archived.html.erb
<div class="w-100 d-flex justify-content-center align-items-center">
<div class="w-50 d-flex flex-column justify-content-center align-items-center">
<div id="archived_posts">
  <% if @posts.present? %>
    <%= render 'posts/posts_list', posts: @archivedposts %>
  <% else %>
    <p class="m-2 p-2 text-center">No archived posts found.</p>
  <% end %>
</div>
</div>

app/views/posts/_comment_list.html.erb
<% if defined?(post) && post.present? %>
  <div id="comments-list-<%= post.id %>">
    <% post.comments.each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  </div>
<% else %>
  <p>No comments available.</p>
<% end %>

app/views/posts/_like_icon.html.erb
<div id="like-icon-post-<%= post.id %>">
  <% if post.liked_by?(current_user) %>
    <%= button_to like_path(post.likes.find_by(user: current_user)),
                  method: :delete,
                  class: "text-decoration-none border-0",
                  data: { turbo_frame: "like-icon-post-#{post.id}" } do %>
      <i class="bi bi-heart-fill fs-4 text-danger"></i>
    <% end %>
  <% else %>
    <%= button_to post_likes_path(post),
                  method: :post,
                  class: "text-decoration-none border-0",
                  data: { turbo_frame: "like-icon-post-#{post.id}" } do %>
      <i class="bi bi-heart fs-4 text-muted"></i>
    <% end %>
  <% end %>
</div>

app/views/posts/_like_text.html.erb
<strong>
    <% likes.each_with_index do |like, index| %>
    <% if likes.size ==1 %>
    <%= like.user.name %>
  </strong> likes this
  <% elsif like == likes.last %>
  </strong>and<strong>
    <%= + like.user.name %></strong> like this
  <% elsif index > 1 %>
  </strong> <%= "and" + (likes.size-index).to_s + "others" %> like this
  <% break %>
  <% elsif index==likes.size-2 || index == 1 %>
  <%= like.user.name %>
  <% else %>
  <%= like.user.name + "," %>
  <% end %>
  <% end %>
</strong>

app/views/posts/_photos.html.erb
<%= link_to post_path(post) do %>
  <% if post.images.size == 1 %>
  <%= image_tag url_for(post.images.first), class: "img-fluid w-100" %>
  <% elsif post.images.size > 1 %>
  <div id="carousel-post-<%= post.id %>" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% post.images.each_with_index do |image, index| %>
      <div class="carousel-item <%= 'active' if index.zero? %>">
        <%= image_tag url_for(image), class: "img-fluid w-100" %>
      </div>
      <% end %>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carousel-post-<%= post.id %>" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carousel-post-<%= post.id %>" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <% end %>
<% end %>

app/views/posts/_posts_list.html.erb
<% posts.each do |post| %>
<div class="card my-3 p-2" id="post_<%= post.id %>">
  <div class="p-3 pb-1 pt-1 fs-5 d-flex">
    <%= link_to user_path(post.user), style: "text-decoration: none; " do %>
    <%= avatar_or_initial(post.user) if post.user.present? %>
    <% end %>

    <div class="d-flex w-100 justify-content-between align-items-center">
      <%= link_to user_path(post.user), style: "text-decoration: none; color:#262626; margin-left:12px;", title: post.user.name do %>
      <strong class="ml-2"><%= post.user.name %></strong>
      <% end %>

      <% if post.user == current_user %>

       <% if post.archived? %>
          <%= button_to "Unarchive", unarchive_post_path(post), method: :patch, class: "btn btn-success btn-sm", data: { turbo_stream: true } %>
        <% else %>
          <%= button_to "Archive", archive_post_path(post), method: :patch, class: "btn btn-warning btn-sm", data: { turbo_stream: true } %>
       <% end %>

       <%= button_to post_path(post), method: :delete, class: "ms-auto mx-0 border-0 bg-transparent" do %>
        <i class="bi bi-trash fs-6 text-muted"></i>
        <% end %>
      <% end %>
    </div>

  </div>
   <hr class="mt-1">

  <div class="p-3 pt-0 pb-2 w-100 ">
    <%= render "posts/photos", {post: post} %>
  </div>


  <div class="p-2 pt-0">
    <div class="row my-3 align-items-center">
      <div class="d-flex w-100 justify-content-between">
        <div class="d-flex">
          <%= render 'posts/like_icon', post: post %>
            <a href="#" class="text-decoration-none ms-3">
            <i class="bi bi-chat fs-4 text-muted"></i>
            </a>
        </div>
        <%= render "bookmarks/bookmark_icon", post: post %>

      </div> 
    </div>     

    <div class="fs-6">
      <span><strong><%= post.user.name %></strong></span>
      <span><%= post.content %></span>
      <br>
      <span class="ms-2"><%= post.likes.size %> <strong> Likes </strong></span>
    </div>

     <div id="like-text-post-<%= post.id.to_s %>" >
        <%= render "posts/like_text", {likes: post.likes} %>
      </div> 
        
        <!-- Display Comments -->
    <div id="comment-form-post-<%= post.id.to_s %>">
     <%= render "posts/comment_list", {post: post} %>
    </div> 


    <div class="text-muted mt-2 fs-9">
      <%= link_to time_ago_in_words(post.created_at).upcase + " AGO", post_path(post) %>
    </div>
    <hr class="mb-0">

       <!-- New Comment Form -->
      <%= turbo_frame_tag "new-comment-post-#{post.id}" , class:"row my-1" do %>
       <%= render 'comments/form', post: post %>
       <% end %>

  </div>
</div>
<% end %>

app/views/posts/archive.turbo_stream.erb
<%= turbo_stream.remove "post_#{@post.id}" %>

app/views/posts/archived.html.erb
<div class="w-100 d-flex justify-content-center align-items-center">
<div class="w-50 d-flex flex-column justify-content-center align-items-center">
<h2 class="mt-2">Archived Posts</h2>

<div id="archived_posts">
  <% if @posts.present? %>
    <%= render 'posts/posts_list', posts: @posts %>
  <% else %>
    <p class="m-2 p-2">No archived posts found.</p>
  <% end %>
</div>
</div>

app/views/posts/index.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11">
    <div class="card">
      <div class="card-header fw-bold">
        Create Post
      </div>
      <div class="card-body p-2">
        <div class="ml-4">
          <%= form_for @post, html: { multipart: true, class: "dropzone upload-images border-0" } do |f| %>
            <div class="form-group row mt-2">
              <div class="col-auto pl-2 pr-0">
                <%= avatar_or_initial(current_user) %>
              </div>
              <div class="col px-0">
                <%= f.text_area :content, class: "form-control", placeholder: "Say something about this ...", style: "resize: none; border:1px solid #dedefc; width:95%;" %>
              </div>
            </div>

            <%= f.file_field :images, type: :file, multiple: true, class: "d-none", id: "hiddenFileInput" %>

            <div class="dz-message m-0"></div>
            <div class="dropzone-previews mt-2">
              <label for="hiddenFileInput" class="dropzone-previews mb-3 mt-2">
                <div class="d-flex align-items-center justify-content-center rounded-1 p-5 m-1"
                     style="height: 120px; width: 160px; border:2px dashed #dedefc; cursor: pointer;">
                  <i class="bi bi-plus fs-1 fw-bold" aria-hidden="true" style="color:grey;"></i>
                </div>
              </label>
            </div>
            <%= f.submit "Post", class: "btn btn-primary" %>
          <% end %> 
        </div>
      </div>
    </div>

    <div id="posts">
      <%= render 'posts/posts_list', posts: @posts %>
    </div> 

  </div>
  <br>
  <!-- Pagination Controls -->
</div>

app/views/posts/show.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="row col-xl-10 col-lg-11 col-12">
    <div class="col-lg-8 col-md-7 px-0 d-flex" style="margin: -10px 0; background-color: #fafafa; ">
      <div class="align-self-center">
        <div class="p-3 pt-0 pb-2 w-100 ">
          <%= render "photos", {post: @post} %>
        </div>
      </div>
    </div>

    <div class="col-lg-4 col-md-5 mt-sm-4 mt-md-0 py-2 mb-4" style="border:1px solid #dedefc; border-radius:20px">
      <div class="row px-3 d-flex align-items-center" >

        <div class="d-flex w-100 justify-content-between align-items-center">
         <div class="d-flex align-items-center fs-4">
         <%= link_to user_path(@post.user), style: "text-decoration: none;" do %>
         <%= avatar_or_initial(@post.user) %>
        <% end %>

        <%= link_to user_path(@post.user), style: "text-decoration: none; color:#262626; margin-left:12px;", title: @post.user.name do %>
        <strong><%= @post.user.name %></strong>
        <% end %>
        </div>

        <% if @post.is_belongs_to? current_user %>
          <%= button_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto border-0 bg-transparent" do %>
          <i class="bi bi-trash fs-6 text-muted"></i>
           <% end %>
        <% end %>
        </div>
      </div>
      <hr class="mb-0">
      <div class="py-2" style="height: 160px; overflow: auto;">
        <% if @post.content.present? %>
        <div>
          <span><strong><%= @post.user.name %></strong></span>
          <span><%= @post.content %></span>
          <br>
          <span class="ms-2"><%= @post.likes.size %> <strong> Likes </strong></span>
        </div>
         <% end %>
        <!--load comment -->
        <%= render "comment_list", post: @post %>
      </div>
      <hr class="mt-0">

      <div class="row my-3 align-items-center">
        <div class="d-flex w-100 justify-content-between">
          <div class="d-flex">
            <%= render 'like_icon', post: @post %>
             <a href="#" class="text-decoration-none ms-3">
              <i class="bi bi-chat fs-4 text-muted"></i>
             </a>
          </div>
          <%= render "bookmarks/bookmark_icon", post: @post %>

      </div>
      </div>
      
      <div id="like-text-post-<%= @post.id.to_s %>" >
        <%= render "like_text", {likes: @likes} %>
      </div> 

      <div class="text-muted mt-2 fs-9">
        <%= link_to time_ago_in_words(@post.created_at).upcase + " AGO", post_path(@post) %>
      </div>
      <hr class="mb-0">

       <!-- New Comment Form -->
      <%= turbo_frame_tag "new-comment-post-#{@post.id}" , class:"row my-3" do %>
       <%= render 'comments/form', post: @post %>
       <% end %>

    </div>
  </div>
</div>